
spring:
  output.ansi.enabled: always

temporal:
  # host: localhost
  # port: 7233
  workflow-defaults:
    activity-pool-size: 100
    execution-timeout: 1000
    execution-timeout-unit: SECONDS
    task-queue: DEFAULT
    workflow-pool-size: 50
  workflows:
    ticket_workflow:
      activity-pool-size: 100
      execution-timeout: 1000
      execution-timeout-unit: SECONDS
      task-queue: TICKETEVALUATIONTASK
      workflow-pool-size: 50
